In [1]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd
import tflearn

curses is not supported on this machine (please install/reinstall curses for an optimal experience)


In [2]:
df = pd.read_csv('D:\Working\TensorFlowTry\how_to_do_math_for_deep_learning-master\database.csv')

In [3]:
df = df[['Latitude', 'Longitude', 'Magnitude', 'Depth']]
print(df.head(10))

   Latitude  Longitude  Magnitude  Depth
0    19.246    145.616        6.0  131.6
1     1.863    127.352        5.8   80.0
2   -20.579   -173.972        6.2   20.0
3   -59.076    -23.557        5.8   15.0
4    11.938    126.427        5.8   15.0
5   -13.405    166.629        6.7   35.0
6    27.357     87.867        5.9   20.0
7   -13.309    166.212        6.0   35.0
8   -56.452    -27.043        6.0   95.0
9   -24.563    178.487        5.8  565.0


In [4]:
x_vals = df.drop('Magnitude',axis=1)
y_vals = df['Magnitude']
x_train, x_test, y_train, y_test = train_test_split(x_vals, y_vals, test_size=0.1, random_state=0)

In [5]:
mms = MinMaxScaler()
print(x_train[:10])
print()
x_train = mms.fit_transform(x_train)
x_test = mms.transform(x_test)
print(x_train[:10])

       Latitude  Longitude  Depth
3539    -6.5900   155.0540   49.0
2395   -11.1600   162.1730   15.0
2285     0.9220   -28.2800   10.0
9365   -56.4040  -121.9640   10.0
21670   -5.2990   151.5190   60.0
3337    61.9090  -149.7380   66.0
21436  -20.8960  -174.1940   11.0
10070   -6.2450   154.7870   59.4
22884    6.2386   147.6443   13.0
9586   -19.0160   176.6520   33.0

[[ 0.43222859  0.93071015  0.07145914]
 [ 0.4042064   0.95048542  0.02296391]
 [ 0.47829046  0.42144196  0.01583226]
 [ 0.12678051  0.16120502  0.01583226]
 [ 0.44014471  0.92089057  0.08714877]
 [ 0.85224883  0.08405395  0.09570675]
 [ 0.34450747  0.01611967  0.01725859]
 [ 0.43434405  0.92996847  0.08629297]
 [ 0.51089064  0.91012736  0.02011125]
 [ 0.3560352   0.99070543  0.04863785]]


In [6]:
y_train = y_train.reshape([-1,1])
y_test = y_test.reshape([-1,1])

C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  if __name__ == '__main__':
C:\Users\user\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  from ipykernel import kernelapp as app


In [ ]:
'''mlp = MLPRegressor(random_state=0, hidden_layer_sizes=(100,100), max_iter=600,  alpha=0.001)
params = {
          'alpha': list(np.logspace(-3.5,1,5)),
          'learning_rate_init': list(np.logspace(-3,1,4))}
gs = GridSearchCV(mlp, params, scoring='r2')
lr = LinearRegression()'''

In [ ]:
'''lr.fit(x_train, y_train)'''

In [ ]:
'''yy = lr.predict(x_train)
print(yy[:10])
print(y_train[:10])'''

In [ ]:
'''print(lr.score(x_train, y_train))'''

In [7]:
input_ = tflearn.input_data(shape=[None,3])
linear = tflearn.fully_connected(input_,1, activation='linear')
regression = tflearn.regression(linear, optimizer='sgd', loss='mean_square', metric='R2', learning_rate=0.01)
m=tflearn.DNN(regression)
m.fit(x_train, y_train, n_epoch=10, show_metric=True, batch_size=32)

Training Step: 6589  | total loss: 0.22256 | time: 5.108s
| SGD | epoch: 010 | loss: 0.22256 - R2: 0.9912 -- iter: 21056/21070
Training Step: 6590  | total loss: 0.21451 | time: 5.118s
| SGD | epoch: 010 | loss: 0.21451 - R2: 0.9942 -- iter: 21070/21070
--


In [12]:
yy = m.predict(x_test)
print(yy[:10])
print(y_test[:10])
print(m.evaluate(x_test,y_test))

[[ 5.89757347]
 [ 5.91938257]
 [ 5.93642426]
 [ 5.83411837]
 [ 5.88634396]
 [ 5.92642069]
 [ 5.88477898]
 [ 5.83923292]
 [ 5.91131878]
 [ 5.80771112]]
[[ 5.9]
 [ 6.1]
 [ 5.5]
 [ 5.5]
 [ 7.5]
 [ 6.1]
 [ 5.9]
 [ 6.2]
 [ 5.5]
 [ 5.7]]
[0.9946622262135415]
